priority = "Normal"
hidden = false
icon = """
...#####...
.##..#..##.
#....#....#
#....#....#
#....#....#
#....###..#
#.........#
#.........#
#.........#
.##.....##.
...#####...
"""

[category]
ko = "도구"
en = "Utility"
ja = "ユーティリティ"


[name]
ko = "시계"
en = "Clock"
ja = "アナログ時計"

[description]
ko = "현재 시간을 알려주는 아날로그 시계"
