[package]
name = "weather"

version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
sdk = { path = "../../sdk" }
graphics = { path = "../../extensions/graphics" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
libm = { workspace = true }
log = "0.4.29"
